<?php

/**
 * Default home page view
 *
 * @author
 * @version
 */

$this->headTitle($this->title);
$this->placeholder('title')->set($this->title);
?>

<div class="btn-toolbar">
	<div class="btn-group">
		<a class="btn" href="<?php echo $this->url(array('action'=>'edit'))?>">Edit</a>
	</div>
</div>

<div>
	<div>
<?php if ($this->user) { $user = $this->user;?>
		<div class="editform">
		<h2><?php echo $user->username?> Profile</h2>
		<dl>
			<dt>Email:</dt>
			<dd><?php echo $user->email?></dd>
			<dt>Real Name:</dt>
			<dd><?php echo $user->realname?></dd>
			<dt>Register Time</dt>
			<dd><?php echo $user->registerTime;?></dd>
		</dl>
		<h2>Roles</h2>
		<dl>
		<?php if (count($this->roles)):?>
		<?php foreach ($this->roles as $role):?>
			<dt><?php echo $role->name;?></dt>
			<dd><?php echo $role->description;?></dd>
		<?php endforeach;?>
		<?php else:?>
			<dt>No role</dt>
		<?php endif;?>
		</dl>
		</div>
<?php }?>
	</div>
</div>