<?php

/**
 * user login
 *
 * @author
 * @version
 */

$this->headLink()->appendStylesheet($this->baseUrl('/styles/login.css'));
?>

<div class="loginform">
<h1>Login to System</h1>
<?php echo $this->form;?>
</div>

<div class="info">
<h2>About</h2>
Zend Framework 1 Example: User Management System.<br />
<h3>News</h3>
<ol>
	<li>Role based Access Control</li>
	<li>New UI style</li>
	<li>DataGrid</li>
	<li>Loging/Logout worked.</li>
	<li>Modular Model loader plugin(set_include_path)</li>
	<li>Modular ErrorController plugin</li>
	<li>Modular layout plugin</li>
</ol>
</div>

<?php $this->inlineScript()->captureStart();?>
$(document).ready(function() {
	$("#username").focus();
});
<?php $this->inlineScript()->captureEnd();?>