<?php echo $this->doctype();?>

<html lang="zh">
<head>
<?php echo $this->headMeta()?>

<?php echo $this->headTitle('Example');?>

<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->baseUrl('/images/favicon.ico')))
          //->prependStylesheet('http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css')
          ->prependStylesheet($this->baseUrl('/css/style.css'))
          ->prependStylesheet($this->baseUrl('/css/bootstrap-responsive.min.css'))
          ->prependStylesheet($this->baseUrl('/css/bootstrap.min.css'))
?>

<?php echo $this->headStyle()?>

<?php
echo $this->headScript()
          ->appendFile($this->baseUrl('/js/html5shiv.js'), 'text/javascript', array('conditional' => 'IE'))
          ->prependFile('http://code.jquery.com/ui/1.9.2/jquery-ui.js')
          ->prependFile('http://code.jquery.com/jquery-1.8.3.js')?>

</head>

<body>

	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
				</a> <a href="/" class="brand">Zend Framework 1.x Example</a>
				<div class="nav-collapse">
					<ul class="nav">
						<li class="active"><a href="<?php echo $this->url(array('controller'=>'index','action'=>'index'))?>">Home</a></li>
						<li><a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'index', 'module'=>'default'), 'default', true)?>">个人中心</a></li>
						<li><a href="<?php echo $this->url(array('controller'=>'system', 'action'=>'settings', 'module'=>'default'), 'default', true)?>">系统设置</a></li>
						<li><a href="https://github.com/kenchou/Zf1Example-UserManagement">源代码下载</a></li>
						<li><a href="http://scicooking.com/ken.html">关于作者</a></li>
					</ul>
				</div>
				<!--/.nav-collapse -->
				<div style="float:right;color:white;">
<?php if($this->authIdentity() === null){?>
		<a href="<?php echo $this->url(array('controller'=>'auth','action'=>'login'), 'default',true)?>">Login</a>
		| <a href="<?php echo $this->url(array('controller'=>'member','action'=>'register'), 'default',true)?>">Register</a>
<?php }else{ ?>
		<a href="<?php echo $this->url(array('controller'=>'member','action'=>'index'), 'default',true)?>"><?php echo $this->authIdentity(); ?></a>
		| <a href="<?php echo $this->url(array('controller'=>'auth','action'=>'logout'), 'default',true)?>">Logout</a>
<?php } ?>
				</div>
			</div>
		</div>
	</div>


<div class="container">
<?php echo $this->layout()->content?>
</div>

<footer>
</footer>
<?php echo $this->inlineScript()?>
</body>
</html>