<?php echo $this->doctype();?>

<html lang="zh">
<head>
<?php echo $this->headMeta()?>

<?php echo $this->headTitle('Example');?>

<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->baseUrl('/images/favicon.ico')))
          ->prependStylesheet($this->baseUrl('/css/black-tie/jquery-ui-1.8.16.custom.css'))
          ->prependStylesheet($this->baseUrl('/css/style.css'))
          ->prependStylesheet($this->baseUrl('/css/bootstrap-responsive.min.css'))
          ->prependStylesheet($this->baseUrl('/css/bootstrap.min.css'))
?>

<?php echo $this->headStyle()?>

<?php
echo $this->headScript()
          ->appendFile($this->baseUrl('/js/html5shiv.js'), 'text/javascript', array('conditional' => 'IE'))
          ->prependFile($this->baseUrl('/js/jquery-ui-1.8.16.custom.min.js'))
          ->prependFile($this->baseUrl('/js/jquery-1.6.2.min.js'))?>

</head>

<body>

	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
				</a> <a href="/" class="brand">Zend Framework 1.x Example</a>
				<div class="nav-collapse">
					<ul class="nav">
						<li class="active"><a href="/">Home</a></li>
						<li><a href="/user/profile">个人中心</a></li>
						<li><a href="/settings">系统设置</a></li>
						<li><a href="https://github.com/kenchou/Zf1Example-UserManagement">源代码下载</a></li>
						<li><a href="http://scicooking.com/ken.html">关于作者</a></li>
					</ul>
				</div>
				<!--/.nav-collapse -->
				<div style="float:right;color:white;"><a href="<?php echo $this->url(array('controller'=>'user','action'=>'login'))?>">Login</a></div>
			</div>
		</div>
	</div>


<div class="container">
<?php echo $this->layout()->content?>
</div>

<footer>
</footer>
<?php echo $this->inlineScript()?>
</body>
</html>