<?php

/**
 * Default home page view
 *
 * @author
 * @version
 */
$_activeController = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
?>

<div>
	<ul class="nav nav-tabs">
		<li<?php if('user' == $_activeController){?> class="active"<?php }?>><a href="<?php echo $this->url(array('controller'=>'user','action'=>'list'), 'default', true)?>">Account</a></li>
		<li<?php if('role' == $_activeController){?> class="active"<?php }?>><a href="<?php echo $this->url(array('controller'=>'role','action'=>'list'), 'default', true)?>">Role</a></li>
		<li<?php if('resource' == $_activeController){?> class="active"<?php }?>><a href="<?php echo $this->url(array('controller'=>'resource','action'=>'list'), 'default', true)?>">Resource</a></li>
		<li<?php if('acl' == $_activeController){?> class="active"<?php }?>><a href="<?php echo $this->url(array('controller'=>'acl','action'=>'list'), 'default', true)?>">Access Control List</a></li>
	</ul>
</div>
