<div class="hero-unit">
	<h1>Welcome to <span class="zf-green">Zend Framework</span> Example!</h1>
	<p>用户管理栗子</p>
	<p><a href="https://github.com/kenchou/Zf1Example-UserManagement" class="btn btn-success btn-large">访问GitHub代码库»</a></p>
</div>

<div class="row">
	<div class="span4">
		<h2>用户管理</h2>
		<ul>
			<li><a href="<?php echo $this->url(array('controller'=>'user','action'=>'list'), 'default', true)?>">用户列表</a></li>
		</ul>
		<p><a href="<?php echo $this->url(array('controller'=>'user','action'=>'list'), 'default', true)?>" class="btn btn-success">帐号管理»</a></p>
	</div>

	<div class="span4">
		<h2>组织机构管理</h2>
		<ul>
			<li><a href="<?php echo $this->url(array('controller'=>'role','action'=>'list'), 'default', true)?>">角色列表</a></li>
			<li><a href="<?php echo $this->url(array('controller'=>'acl','action'=>'index'), 'default', true)?>">权限设置</a></li>
		</ul>
		<p><a href="<?php echo $this->url(array('controller'=>'role','action'=>'index'), 'default', true)?>" class="btn btn-success">组织机构管理  »</a></p>
	</div>

	<div class="span4">
		<h2>系统设置</h2>

		<ul>
			<li><a href="<?php echo $this->url(array('controller'=>'resource','action'=>'list'), 'default', true)?>">系统资源</a></li>
			<li><a href="<?php echo $this->url(array('controller'=>'acl','action'=>'index'), 'default', true)?>">权限设置</a></li>
		</ul>

		<p><a href="<?php echo $this->url(array('controller'=>'acl','action'=>'index'), 'default', true)?>" class="btn btn-success">权限设置  »</a></p>
	</div>

	<div class="span4">
		<h2>帮助与支持</h2>
	</div>

</div>