<div class="hero-unit">
		<h1>Welcome to <span class="zf-green">Zend Framework</span> Example!</h1>
		<p>用户管理栗子</p>
		<p><a href="https://github.com/kenchou/Zf1Example-UserManagement" class="btn btn-success btn-large">访问GitHub代码库»</a></p>
</div>

<div class="row">
	<div class="span4">
		<h2>用户管理</h2>
		<p><a target="_blank" href="http://www.xunbaotuan.com">用户管理</a></p>
		<p><a href="http://www.xunbaotuan.com" class="btn btn-success">用户管理»</a></p>
	</div>

    <div class="span4">
      <h2>组织机构管理</h2>
       <p><a target="_blank" href="http://www.lensgo.cn">组织机构管理</a></p>
      <p><a href="http://www.lensgo.cn" class="btn btn-success">组织机构管理  »</a></p>
    </div>

    <div class="span4">
		<h2>系统设置</h2>
		<p>系统设置</p>
	</div>

    <div class="span4">
		<h2>帮助与支持</h2>
	</div>

</div>