<?php

/**
 * Default home page view
 *
 * @author
 * @version
 */

$this->headTitle($this->title);
$this->placeholder('title')->set($this->title);
?>
<?php echo $this->render('acl/_tabs.phtml')?>
<?php echo $this->render('user/_toolbar.phtml')?>

<div class="ui-tabs ui-widget ui-widget-content ui-corner-all" id="tabs">
	<div class="ui-tabs-panel ui-widget-content ui-corner-bottom">
		<form id="listform" action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'delete'), null, true);?>" method="post">

		<div class="datagrid dateList">
			<table class="table table-bordered">
				<caption>User list</caption>
				<tr>
					<th>ID</th>
					<th>Username</th>
					<th>Email</th>
					<th>Status</th>
					<th>Actions</th>
				</tr>
<?php foreach ($this->users as $user) {?>
				<tr>
					<td><?php echo $user->id?></td>
					<td><a href="<?php echo $this->url(array('controller'=>'user','action'=>'view','id'=>$user->id))?>"><?php echo $user->username?></a></td>
					<td><?php echo $user->email?></td>
					<td><?php echo $user->getStatusText()?></td>
					<td>
						<a href="<?php echo $this->url(array('controller'=>'user','action'=>'view','id'=>$user->id))?>">View</a> |
						<a href="<?php echo $this->url(array('controller'=>'user','action'=>'edit','id'=>$user->id))?>">Edit</a> |
						<a href="<?php echo $this->url(array('controller'=>'user','action'=>'set-status','id'=>$user->id, 'status'=>!$user->status))?>"><?php echo $user->status ? 'Enable' : 'Disable'?></a>
					</td>
				</tr>
<?php }//endforeach?>
			</table>
		</div>
		</form>
		<div class="pannelFloat"></div>
	</div>
</div>
