production:
    phpSettings:
        display_startup_errors: false
        display_errors: false

    includePaths:
        library: APPLICATION_PATH/../library
    bootstrap:
        path: APPLICATION_PATH/Bootstrap.php
        class: "Bootstrap"
    appnamespace: "Application"
    autoloaderNamespaces:
        - Ken
#    pluginPaths:
#        Application_Plugin: APPLICATION_PATH/plugins/  # default plugin defined in Module_Autoloader 

    resources:
        frontController:
            controllerDirectory: APPLICATION_PATH/controllers
            params:
                displayExceptions: false
            actionHelperPaths:
                Application_Controller_Action_Helper: APPLICATION_PATH/helpers
            plugins:
                - Application_Plugin_Auth
                - Application_Plugin_Acl
        layout:
            layoutPath: APPLICATION_PATH/views/scripts/
        view:
            doctype: "XHTML5"
            charset: "UTF-8"
            encoding: "UTF-8"
            helperPath:
                Application_View_Helper: APPLICATION_PATH/views/helpers
        multidb:
            defaultMetadataCache: "metadata"    # use cachemanager: metadata
            default:
                adapter: "Pdo_Mysql"
                host: "127.0.0.1"
                username: "root"
                password: "123456"
                dbname: "example"
                profiler:
                    enabled: "true"
                    class: "Zend_Db_Profiler_Firebug"
                default: true
        cachemanager:
            metadata:           # Cache for MetaData of DbTable
                frontend:
                    name: "Core"
                    customFrontendNaming: false
                    options:
                        caching: false      # enable/disable cache
                        lifetime: 7200
                        automatic_serialization: true
                backend:
                    name: "Apc"
                frontendBackendAutoload: false
            default:
                frontend:
                    customFrontendNaming: false
                    name: "Core"
                    options:
                        caching: false      # enable/disable cache
                        lifetime: 7200
                        automatic_serialization: true
                backend:
                    name: "Apc"
                frontendBackendAutoload: false
        log:
            firebug:
                writerName: "Firebug"
                writerParams:
                    application: "example"

########################
# staging env
########################
staging:
    _extends: production

########################
# qa env
########################
testing:
    _extends: production
    phpSettings:
        display_startup_errors: true
        display_errors: true

########################
# dev env
########################
development:
    _extends: production
    phpSettings:
        display_startup_errors: true
        display_errors: true
    resources:
        frontController:
            params:
                displayExceptions: true