auth:
    login:
        action: /{module}/{controller}/{action}
        method: "post"
        elements:
            username:
                type: "text"
                options:
                    label: "Username"
                    required: true
                    validators:
                        regex:
                            validator: "regex"
                            options: 
                                pattern: "/^[a-zA-Z_][a-zA-Z0-9_@\.-]*$/"
                        strlen:
                            validator: "StringLength"
                            options: 
                                min: 3
                                max: 32
                    filters:
                        lower:
                            filter: "StringToLower"
                        trim:
                            filter: "StringTrim"
            password:
                type: "password"
                options:
                    label: "Password"
                    validators:
                        strlen:
                            validator: "StringLength"
                            options:
                                min: 8
                    required: true
            submit:
                type: "submit"
                options:
                    label: "Login"
                    ignore: true
                    decorators:
                        viewHelper: "ViewHelper"
                        htmlTag:
                            decorator: "HtmlTag"
                            options:
                                tag: "dd"
                                class: "singleButton"

user:
    register:
        action: /{module}/{controller}/{action}
        method: "post"
        elements:
            username:
                type: "text"
                options:
                    label: "Username"
                    required: true
                    validators:
                        regex:
                            validator: "regex"
                            options:
                                pattern: "/^[a-zA-Z_][a-zA-Z0-9_@\.-]*$/"
                        strlen:
                            validator: "StringLength"
                            options:
                                min: 3
                                max: 32
                    filters:
                        lower:
                            filter: "StringToLower"
                        trim:
                            filter: "StringTrim"
            email:
                type: "text"
                options:
                    label: "Email"
                    required: true
                    validators:
                        regex:
                            validator: "regex"
                            options:
                                pattern: "/^[a-zA-Z_][a-zA-Z0-9_@\.-]*$/"
                        strlen:
                            validator: "StringLength"
                            options:
                                min: 3
                                max: 320
                    filters:
                        lower:
                            filter: "StringToLower"
                        trim:
                            filter: "StringTrim"
            password:
                type: "password"
                options:
                    label: "Password"
                    validators:
                        strlen:
                            validator: "StringLength"
                            options:
                                min: 8
                    required: true
            password2:
                type: "password"
                options:
                    label: "Confirm Password"
                    validators:
                        strlen:
                            validator: "StringLength"
                            options:
                                min: 8
                    required: true
            submit:
                type: "submit"
                options:
                    label: "Register"
                    ignore: true
                    decorators:
                        viewHelper: "ViewHelper"
                        htmlTag:
                            decorator: "HtmlTag"
                            options:
                                tag: "dd"
                                class: "singleButton"
profile:
    edit:
        action: /{module}/{controller}/{action}
        method: "post"
        attribs:
            enctype: "multipart/form-data"
        elements:
            avatar:
                type: "File"
                options:
                    label: "Avatar"
                    description: "You can upload *.jpg, *.png and *.gif"
                    require: false
                    validators:
                        ext:
                            validator: "Extension"
                            extension: "jpg,jpeg,png,gif"
                            messages:
                                fileExtensionFalse = "It only supports jpg,jpeg,png,gif format."

            realname:
                type: "text"
                options:
                    label: "Real Name"
                    required: false
                    validators:
                        strlen:
                            validator: "StringLength"
                            options: 
                                min: 3
                                max: 32
                    filters:
                        lower:
                            filter: "StringToLower"
                        trim:
                            filter: "StringTrim"
            birthday:
                type: "text"
                options:
                    label: "Birthday"
                    required: false
                    validators:
                        strlen:
                            validator: "StringLength"
                            options: 
                                min: 3
                                max: 32
                    filters:
                        lower:
                            filter: "StringToLower"
                        trim:
                            filter: "StringTrim"

            submit:
                type: "submit"
                options:
                    label: "Update"
                    ignore: true
                    decorators:
                        viewHelper: "ViewHelper"
                        htmlTag:
                            decorator: "HtmlTag"
                            options:
                                tag: "dd"
                                class: "singleButton"